name: Patreon -> Google Drive

on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
      types:
      - webhook
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - run: npm ci
    - run: node ./src/main.js
      env:
        PATREON_ACCESS_TOKEN: ${{ secrets.PATREON_ACCESS_TOKEN }}
        DRIVE_CLIENT_ID: ${{ secrets.DRIVE_CLIENT_ID }}
        DRIVE_CLIENT_SECRET: ${{ secrets.DRIVE_CLIENT_SECRET }}
        DRIVE_REDIRECT_URI: ${{ secrets.DRIVE_REDIRECT_URI }}
        DRIVE_REFRESH_TOKEN: ${{ secrets.DRIVE_REFRESH_TOKEN }}
        DRIVE_REWARDS_DIR_NAME: ${{ secrets.DRIVE_REWARDS_DIR_NAME }}
        DRIVE_TIERS_DIR_NAME: ${{ secrets.DRIVE_TIERS_DIR_NAME }}
